function escape(value: string) {
  return value.replace(
    /[&<>"']/g,
    (char) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        char
      ]!,
  );
}

export function authPage(
  mode: "login" | "password",
  options: { error?: string; csrf?: string; required?: boolean } = {},
) {
  const login = mode === "login";
  const title = login
    ? "Bem-vindo de volta."
    : options.required
      ? "A tua primeira entrada."
      : "Alterar palavra-passe";
  return `<!doctype html><html lang="pt-PT"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${login ? "Entrar" : "Alterar palavra-passe"} | Dashboard Geral</title><style>
  *{box-sizing:border-box}body{margin:0;font:15px Arial,Helvetica,sans-serif;background:#f6f8fc;color:#243046;min-height:100vh;display:grid;place-items:center;padding:24px}.shell{width:min(920px,100%);display:grid;grid-template-columns:1fr 1fr;background:white;border:1px solid #e7ebf2;border-radius:22px;overflow:hidden;box-shadow:0 25px 80px #253a7010}.intro{padding:50px 38px;background:#edf2ff;display:flex;flex-direction:column;justify-content:space-between;gap:70px}.brand{font-size:22px;font-weight:700;letter-spacing:-.7px}.brand span{color:#5472dc}.intro h2{font-size:35px;line-height:1.2;letter-spacing:-1.5px;font-weight:500}.intro p{color:#65738c;line-height:1.8;font-size:13px}.small{font-size:11px;color:#6b7e9e;letter-spacing:1px}.form{padding:48px 38px}h1{font-size:26px;letter-spacing:-.8px;margin:0 0 13px}.description{color:#718096;line-height:1.7;font-size:13px;margin:0 0 30px}label{display:block;font-size:12px;font-weight:600;margin:18px 0 8px}input{width:100%;padding:13px;border:1px solid #d9e0ec;border-radius:8px;font:inherit;font-size:14px;background:#fbfcff;color:#243046}input:focus{outline:2px solid #5472dc;outline-offset:2px}button{width:100%;border:0;border-radius:8px;padding:14px;background:#536edc;color:white;font-weight:600;font-size:13px;cursor:pointer;margin-top:24px}button:focus-visible,a:focus-visible{outline:3px solid #8fa7ff;outline-offset:3px}.error{padding:12px;border-radius:8px;background:#fff0ef;color:#a33835;font-size:13px;line-height:1.6}.hint{font-size:11px;line-height:1.7;color:#718096;margin-top:16px}a{color:#536edc}.secondary{background:transparent;color:#66748d;margin-top:10px}.footer{text-align:center;font-size:11px;color:#8590a3;margin-top:24px}@media(max-width:650px){.shell{grid-template-columns:1fr;max-width:430px}.intro{padding:25px;gap:0}.intro h2,.intro p,.small{display:none}.form{padding:30px 25px}h1{font-size:24px}}
  </style></head><body><div><main class="shell"><aside class="intro"><div class="brand">▦ Dashboard<span>.</span></div><div><h2>O teu trabalho.<br>Tudo no mesmo lugar.</h2><p>Um acesso simples às ferramentas que fazem parte do teu dia.</p></div><span class="small">APLICAÇÕES INTERNAS</span></aside><section class="form"><h1>${title}</h1><p class="description">${login ? "Entra na tua conta para aceder ao teu espaço de trabalho." : options.required ? "Antes de continuar, substitui a palavra-passe temporária por uma palavra-passe só tua." : "Escolhe uma nova palavra-passe para proteger a tua conta."}</p>${options.error ? `<p class="error" role="alert">${escape(options.error)}</p>` : ""}<form method="post" action="${login ? "/auth/login" : "/auth/password"}">${login ? `<label for="email">Email</label><input id="email" name="email" type="email" autocomplete="username" required maxlength="254" placeholder="nome@staples.pt" autofocus>` : `<input type="hidden" name="csrf" value="${escape(options.csrf ?? "")}">`}<label for="password">${login ? "Palavra-passe" : "Palavra-passe atual"}</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="128">${login ? "" : `<label for="newPassword">Nova palavra-passe</label><input id="newPassword" name="newPassword" type="password" autocomplete="new-password" required minlength="12" maxlength="128"><label for="confirmation">Confirmar nova palavra-passe</label><input id="confirmation" name="confirmation" type="password" autocomplete="new-password" required minlength="12" maxlength="128">`}<button type="submit">${login ? "Entrar no dashboard →" : "Guardar e continuar →"}</button></form><p class="hint">${login ? "Primeiro acesso? Utiliza a palavra-passe temporária que recebeste. Será necessário alterá-la antes de entrar." : "Usa pelo menos 12 caracteres. Podes escolher uma frase longa e fácil de recordar. Não reutilizes a palavra-passe temporária."}</p>${login ? "" : `<form method="post" action="/auth/logout"><button class="secondary">Terminar sessão</button></form>`}</section></main><div class="footer">Dashboard Geral · O teu ponto de partida.</div></div></body></html>`;
}
